import CustomError from '../../src/infrastructure/errors/custom.error';
import { readConfiguration } from '../../src/infrastructure/utils/config.utils';

describe('readConfiguration', () => {
  const originalEnvironment = process.env;

  beforeEach(() => {
    process.env = { ...originalEnvironment };
  });

  afterEach(() => {
    process.env = originalEnvironment;
  });

  it('should throw an error with missing config', () => {
    process.env = {};

    const t = () => {
      readConfiguration();
    };
    expect(t).toThrow(CustomError);
  });

  it('should read the API client environment generated by Connect', () => {
    process.env = {
      CTP_API_URL: 'https://api.europe-west1.gcp.commercetools.com',
      CTP_AUTH_URL: 'https://auth.europe-west1.gcp.commercetools.com',
      CTP_CLIENT_ID: '123456789012345678901234',
      CTP_CLIENT_SECRET: '12345678901234567890123456789012',
      CTP_PROJECT_KEY: 'project-key',
      CTP_SCOPE:
        'view_products:project-key view_product_selections:project-key view_categories:project-key',
      RELEWISE_STORE_KEY: 'store-key',
      RELEWISE_DATASET_ID: 'dataset-id',
      RELEWISE_API_KEY: 'api-key',
      RELEWISE_SERVER_URL: 'https://api.relewise.com',
    };

    expect(readConfiguration()).toEqual({
      apiUrl: process.env.CTP_API_URL,
      authUrl: process.env.CTP_AUTH_URL,
      clientId: process.env.CTP_CLIENT_ID,
      clientSecret: process.env.CTP_CLIENT_SECRET,
      projectKey: process.env.CTP_PROJECT_KEY,
      scope: process.env.CTP_SCOPE,
      storeKey: process.env.RELEWISE_STORE_KEY,
      relewise: {
        datasetId: process.env.RELEWISE_DATASET_ID,
        apiKey: process.env.RELEWISE_API_KEY,
        serverUrl: process.env.RELEWISE_SERVER_URL,
      },
    });
  });
});
