name: CI

on: push

env:
  node-version: '20'

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./full-sync
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - run: npm ci
        name: Install dependencies

      - run: npm run build
        name: Build

      - run: npm test
        name: Unit tests